version: '3.6'

services: 
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: atm-machine
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        networks:
            - atm_network
            
    atm:
        image: atm-machine
        restart: always
        build: .
        ports: 
            - "8080:8080"
        networks:
            - atm_network
            
networks:
  atm_network: